### ISSUE TITLE
Challenge 001 Submissions

### ISSUE THREAD

**Issue by timbeaudet** [timbeaudet/knowledge_base#3]
Not an actual issue, but a stub for potentially using issue-comments as a way to submit. Presently submission process is a work-in-progress and subject to changes.

**Submission Example:**  

2019-10-12 Tim Beaudet https://www.turtlebrains.com/
- Task 1 completed
- Recolored the buttons on main menu.
- Made the player jump higher.
- Redid levels 1 and 3 for new jump.

**Comment by rhymu8354** [comment]
2009-10-19 rhymu8354 https://github.com/rhymu8354/MoonUnit

- Established new command-line tool for discovering and running Lua unit tests.
- Made the test runner look and act enough like Google Test to fool existing VSCode plugins.
- Set up the tool's build system so it can either stand alone or be included in a larger project.
- Spent some time writing up what is hopefully a nice README document for the tool.

**Comment by jasonleekennedy** [comment]
Started a 2D ARPG [Top Down] project with the goal of a game in 200 hours:
Video as of 10/16/19 [no significant noticeable visual change after this]
https://youtu.be/DexFp8DUA0U
- 10/11/19 
  - 0.25 - Setup Git project & Initial Godot Files
  - 1.00 - simple map & moving character
- 10/12/19
  - 0.25 - Character Facing Animations
  - 0.25 - Character Running Animations
  - 0.25 - Add collision to tilemap & adjust character collider
  - 0.00 - Center Character collider [make math either later]
  - 0.50 - Make Sword Sprite & Integrate Into Player
  - 0.25 - Test Dummy & Sword Do damage
- 10/13/19
  - 0.25 - Moving Test Dummy w/ Damage, Player Hurt reaction
  - 1.00 - Scene Swapping System
- 10/14/19
  - 0.25 - Persistent Data System
- 10/15/19
  - 0.50 - Save/Load System & simple Main Menu
- 10/16/19
  - 0.75 - Screen Shake, Player Footsteps, Player Sword Swing Sound
  - 0.50 - Game HP Bar & Player HP Score
- 10/17/19
  - 0.25 - Death & Death Screen
- 01/18/19	
  - 0.13 - Player Hurt SFX		
  - 0.33 - Pause Screen		
  - 0.25 - Game Task Planning		
- 01/19/19
  - 0.25 - UI Controller Input Scripting Needs		
  - 0.75- Split UI to Scenes & related decoupling

**Comment by felixsoum** [comment]
2019-10-19 Felix https://store.steampowered.com/app/1173200/Metal_Unit/

- Implemented weapon combo systems.
- Added knockback property to items to be able to push and juggle enemies.
![Nothing_Personal_Kid](https://user-images.githubusercontent.com/6082364/67154262-30a45300-f2c7-11e9-9d8f-df4a972b10f2.gif)
- Integrated animations for the player putting her suit on and off.
![Goodnight_Sweet_Prince](https://user-images.githubusercontent.com/6082364/67154269-4a459a80-f2c7-11e9-8ee4-50424997e29b.gif)
- Created Steam page for the game using tasks I just completed to create gifs.

**Comment by mike-inPrinciple** [comment]
2019.10.12 - 2019.10.19
[ReportForTim.pdf](https://github.com/timbeaudet/knowledge_base/files/3747525/ReportForTim.pdf)

**Comment by JoeCoo7** [comment]
Sorry for the wall of text, I don't have a website for the game yet :(.

- I worked on Wizard Towers full time for about 2 years. 

- Wizard Towers tries to innovate in the RTS genre. It's a game for people who like RTS, but the complicated micro management keeps them from playing. The idea in Wizard Towers is to remove most of the micro- and leave focus on macro-management. This goal is not yet fully achieved due to missing content, but I hope you get the idea already while playing it!

- When I started off, I wrote a devlog https://wizardtowers.tumblr.com/ Unfortunately I stopped writing due to time constraints.

- You can find a lot of gifs I made through out the development here https://giphy.com/channel/joecool

- A small video which I lately recorded in game shows a bigger battle going on https://www.youtube.com/watch?v=dkv8oKcKoaA

- If you want to test the game please checkout the link https://drive.google.com/drive/folders/1nKdCczVmvigoh3yRbdhx1Swpp0YPGDwX?usp=sharing  (Mac and Linux Version are not thoroughly tested and might not work in certain circumstances, also the workers are not yet in the game)

- From 12th of October to 19th of October I worked on adding workers to the game. Here is a draft I made in Magica Voxel 

![workers_storage](https://user-images.githubusercontent.com/696754/67157546-ca9ee680-f32d-11e9-9f38-e9951f2b9f72.png)

- Here is a small gif of the workers doing their job in the game (using old archer gfx, as I haven't yet animated the workers)

![worker_test](https://user-images.githubusercontent.com/696754/67157750-e9eb4300-f330-11e9-8fcb-185a6dba4b18.gif)

- The player can recruit workers in a storage 
- Workers harvest gold and mana, repair buildings and construct buildings automatically
- The player can assign the number of workers via a slider on each of the resources/buildings 
- The buildings now have a different construct animation (before buildings just were created by "magic"
- The feature needs at least another week to fully function in the current game (animate workers, adding carts for workers when harvesting etc.)

**Comment by timbeaudet** [comment]
This Challenge is now over (for a long time) though feel free to try completing it!
